apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-ui
  annotations:
    avp.kubernetes.io/path: "secret/example.yaml"
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: guestbook-ui
  template:
    metadata:
      labels:
        app: guestbook-ui
      annotations:
        test: <secret>
    spec:
      containers:
      - image: gcr.io/heptio-images/ks-guestbook-demo:0.2
        name: guestbook-ui
        ports:
        - containerPort: 80
